### ISSUE TITLE
Загружать с сервера список аппов к установке на дисплеи по-умолчанию

### ISSUE THREAD

**Issue by hacker-cb** [carmodapps/liauto-install-scripts#9]
Сейчаc API https://store.carmodapps.com/api/applications/download с хедером `Accept: text/plain` возвращает список аппов в следующем формате:

`<app_id>|<app_filename>|<app_url>

я предлагаю сделать

`<app_id>|<app_filename>|<app_url>|<screens>`

где `screens` - comma-separated list `[driver|copilot|rear]`

например, `driver,copilot`, `driver,rear`

Это позволит уйти от хардкода списка аппов в инсталлере, и все установщики будут ВСЕГДА ставить то, что рекомендуем мы СРАЗУ.

@kolychev,  на сервере, если апп для Li, нужно добавить три чекбокса, куда по-дефолту мы его ставим.

Сообщи в этом тикете, как сделаешь, я поправлю инсталлер.

**Comment by hacker-cb** [comment]
@kolychev эти галочки сделаешь?

**Comment by kolychev** [comment]
@hacker-cb Сделал галочки в админке и 4 поле в txt формате

**Comment by hacker-cb** [comment]
@kolychev 

1. Они сейчас все активны, это дефолтовое состояние?
2. В сводной таблице в админке бы отображать, где стоят галочки...
